### PR TITLE
React & Redux group project - Space Travelers' Hub

### PR DESCRIPTION
**Pull request by porag-m06**
Hi, this week ```*no coding partner*``` has been assigned to me in my dashboard. Therefore, I am the only one have been working on this project.

[Space Travelers' Hub: Live Demo](https://space-traveler-hub-4dg6.onrender.com/)

**Highlights**
- Upon the first render fetch data from the SpaceX API endpoints.
- Rendered UI lists accordingly
- Written actions for booking rockets and joining missions
- Written actions for canceling rockets and leaving missions
- Rendered My Profile Section with booked rockets and missions list.

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @porag-m06,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Linters passed ✔️
- Readme file professional ✔️
- All components and redux in place ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] I will encourage you to write unit tests with React Testing Library and Jest (for unit tests) for your project so that you will be double sure of what is expected.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by porag-m06** [comment]
@Olamarx  Hi, thanks for the review, however, as per the [instruction](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/project_space_travelers_hub.md) *All tasks should be based on the cards from your Kanban board.*

Writing tests are not mentioned as mandatory, So, it would be great if you could shed some light on that if it could be a blocker on PR approval, please?

Besides, it is doubled the tasks for me already as I don't have any partners assigned this week on my dashboard. 

Thanks

**Review by zieeco — CHANGES_REQUESTED** [review]
Hi @porag-m06,


Hi! 👏, You should add a unit test as part of the project requirement. I understand you've worked on the project alone, but please, kindly add some to meet the project requirement. 


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments below._

- [ ] Kindly add a unit test to meet the remaining part of the project requirement.



## Optional suggestions

- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ridwanediallo — APPROVED** [review]
# STATUS: APPROVED 🟢
## Hi @porag-m06 , 
Congratulations!GIF

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Tests are added and all of then are passing. ✔
- You successfully completed all the requirements.  🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
